---
abstract: '"Beefing" up the RNA sequencing simulator polyester with polyA tails'
author:
  - 'Christos Argyropoulos <chrisarg@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.032, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Bio-SeqAlignment-Examples-TailingPolyester
no_index:
  directory:
    - eg
    - examples
    - inc
    - share
    - t
    - xt
provides:
  Bio::SeqAlignment::Examples::TailingPolyester:
    file: lib/Bio/SeqAlignment/Examples/TailingPolyester.pm
    version: '0.01'
  Bio::SeqAlignment::Examples::TailingPolyester::GSLRNG:
    file: lib/Bio/SeqAlignment/Examples/TailingPolyester/GSLRNG.pm
    version: '0.01'
  Bio::SeqAlignment::Examples::TailingPolyester::PDLRNG:
    file: lib/Bio/SeqAlignment/Examples/TailingPolyester/PDLRNG.pm
    version: '0.01'
  Bio::SeqAlignment::Examples::TailingPolyester::PERLRNG:
    file: lib/Bio/SeqAlignment/Examples/TailingPolyester/PERLRNG.pm
    version: '0.01'
  Bio::SeqAlignment::Examples::TailingPolyester::PERLRNGPDL:
    file: lib/Bio/SeqAlignment/Examples/TailingPolyester/PERLRNGPDL.pm
    version: '0.01'
  Bio::SeqAlignment::Examples::TailingPolyester::SimulateMathGSL:
    file: lib/Bio/SeqAlignment/Examples/TailingPolyester/SimulateMathGSL.pm
    version: '0.01'
  Bio::SeqAlignment::Examples::TailingPolyester::SimulatePDLGSL:
    file: lib/Bio/SeqAlignment/Examples/TailingPolyester/SimulatePDLGSL.pm
    version: '0.01'
  Bio::SeqAlignment::Examples::TailingPolyester::SimulateTruncatedRNG:
    file: lib/Bio/SeqAlignment/Examples/TailingPolyester/SimulateTruncatedRNG.pm
    version: '0.01'
  Bio::SeqAlignment::Examples::TailingPolyester::SimulateTruncatedRNGPDL:
    file: lib/Bio/SeqAlignment/Examples/TailingPolyester/SimulateTruncatedRNGPDL.pm
    version: '0.01'
requires:
  Carp: '0'
  Class::Tiny: '0'
  Math::GSL::CDF: '0'
  PDL: '0'
  PDL::GSL::CDF: '0'
  PDL::GSL::RNG: '0'
  PDL::Lite: '0'
  Package::Stash: '0'
  Role::Tiny: '0'
  Role::Tiny::With: '0'
  strict: '0'
  subs: '0'
  warnings: '0'
version: '0.01'
x_generated_by_perl: v5.38.0
x_serialization_backend: 'YAML::Tiny version 1.74'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
